name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

jobs:
  create_release:
    name: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        run: |
          gh release create "$GITHUB_REF" \
            --repo "$GITHUB_REPOSITORY" \
            --notes "[CHANGELOG.md](https://github.com/figsoda/unnix/blob/$GITHUB_REF/CHANGELOG.md)"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  release:
    name: release
    needs: create_release
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            runner: macos-latest
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies (musl)
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt update
          sudo apt install musl-tools

      - name: Cargo build
        run: |
          rustup toolchain install nightly --profile minimal -t ${{ matrix.target }}
          cargo +nightly build --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: -C strip=symbols

      - name: Upload asset
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # latest
        with:
          tag: ${{ github.ref }}
          file: target/${{ matrix.target }}/release/unnix
          asset_name: unnix-${{ matrix.target }}

  artifacts:
    name: artifacts
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cargo build
        run: |
          rustup toolchain install nightly --profile minimal
          cargo +nightly build
        env:
          GENERATE_ARTIFACTS: artifacts

      # https://reproducible-builds.org/docs/archives/
      - name: Create tarball
        run: |
          tar --xz -cf artifacts.tar.xz artifacts \
            --sort=name \
            --mtime=@0 \
            --owner=0 --group=0 --numeric-owner \
            --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # latest
        with:
          tag: ${{ github.ref }}
          file: artifacts.tar.xz
